services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: mentalorium-app

    container_name: mentalorium-container

    working_dir: /app

    volumes:
      - .:/app

    # Falls du CSVs außerhalb mounten willst:
    # - ./data:/app/data

    command: ["bash"]

    tty: true
    stdin_open: true

    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
